apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-single
  namespace: argocd
spec:
  destination:
    namespace: vm-single
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vm-single/
    repoURL: https://github.com/thegitarist/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true