apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-single
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: victoria-metrics-single
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.8.15
    helm:
      releaseName: victoria-metrics-single

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vm-single

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.