argo-cd:
  global:
    image:
      tag: v2.2.3
  server:
    extraArgs:
      - --insecure
  configs:
    repositories:
      helm-repo:
        name: stable
        type: helm
        url: https://charts.helm.sh/stable
      argocd-repo:
        name: argo-cd
        type: helm      
        url: https://argoproj.github.io/argo-helm