argo-cd:
  server:
    extraArgs:
      - --insecure
    additionalApplications:
      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          helm:
            version: v3
            valueFiles:
            - values.yaml
          path: argocd/
          repoURL: https://github.com/thegitarist/argocd.git
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
      - name: applications
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          path: applications/
          repoURL: https://github.com/thegitarist/argocd.git
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: {}
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$GB0PLIczZYRN5HSiXeALIOBw.52Kqt9R6MSawF0vttESdCs9IC1z6%"
    repositories:
      argocd-repo:
        name: argo-cd
        type: helm      
        url: https://argoproj.github.io/argo-helm
      this-repo:
        name: this-repo
        type: git
        url: https://github.com/thegitarist/argocd.git
      vm-repo:
        name: vm-repo
        type: helm
        url: https://victoriametrics.github.io/helm-charts